/* 

Problem Title: The Report
Problem Url: https://www.hackerrank.com/challenges/the-report

*/

SELECT IIF(GRADES.GRADE >= 8, STUDENTS.NAME, NULL), GRADES.GRADE, STUDENTS.MARKS
FROM GRADES 
JOIN STUDENTS ON STUDENTS.MARKS BETWEEN GRADES.MIN_MARK AND GRADES.MAX_MARK
ORDER BY GRADES.GRADE DESC, STUDENTS.NAME;